- hosts: nx-demo
  become: yes
  roles:
    - role: ansible-role-logstash
      logstash_user: nutanix
      logstash_elasticsearch_hosts: "{{ lookup('env', 'ES_PATH') }}"
      logstash_elasticsearch_user: "{{ lookup('env', 'ES_USER') }}"
      logstash_elasticsearch_password: "{{ lookup('env', 'ES_PASSWD') }}"
